// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using apiUrbanPlanning.Infrastructure.Data;

#nullable disable

namespace apiUrbanPlanning.Migrations
{
    [DbContext(typeof(InfrastructureDbContext))]
    [Migration("20260601120000_addUserRefreshToken")]
    partial class addUserRefreshToken
    {
    }
}
