// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using apiUrbanPlanning.Infrastructure.Data;

#nullable disable

namespace apiUrbanPlanning.Migrations
{
    [DbContext(typeof(InfrastructureDbContext))]
    [Migration("20260511153000_addIbgeIdToSuggestions")]
    partial class addIbgeIdToSuggestions
    {
    }
}

